### ISSUE TITLE
Linux Launcher Crash Report - Fedora 33

### ISSUE THREAD

**Issue by maxrdz** [ToontownRewritten/ToontownReleaseArchive#29]
I tried installing Toontown Rewritten on my Linux system, and was prompted with many error messages, mostly on font configuration errors. Here is my system specifications, resources/libraries installed, and crash log.

System Specifications:

    Operating System - Fedora 33 Workstation
    Architecture - x86-64 (amd64)
    Kernel - 5.10.21 64-bit

    Graphics - NV136 / Mesa Intel® UHD Graphics 630 (CFL GT2)
    Dedicated GPU - Nvidia GTX 1060 Mobile

    Desktop Environment - GNOME 3.38.4
    Windowing System - Wayland

Installed Resources:

    GNU GCC Compiler (Red-Hat)
    Python 3.9.2
    and the others in the requirements from the site
    lol im just really tired right now
    
Launcher Crash Log: 

(... a bunch of Font config errors before the line below.)

    Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'translate'
    Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'selector'
    Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'xmlns:its'
    Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'version'
    Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
    Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
    Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
    Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
    Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
    Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
    Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
    QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
    Qt: Session management error: None of the authentication protocols specified are supported
    Fontconfig warning: FcPattern object weight does not accept value [0 205)
    Unable to obtain remote mirror list! Using local backup instead.
    Segmentation fault (core dumped)

Hope this feedback helps! 👍🏻

**Comment by NathanX-S** [comment]
This repo isn't for game support, or specifically related to rewritten.
