### ISSUE TITLE
macOS-sv1.0.47.31 Client Contribution

### ISSUE THREAD

**Issue by CloudCityDev** [ToontownRewritten/ToontownReleaseArchive#3]
As far as I'm aware, this is the only public macOS client, therefore I'd consider it to be of significance. I found it on an old iMac I have and uploaded it to GitHub a couple months ago. Hopefully Mediafire is acceptable for uploading it.

Mediafire upload:
http://www.mediafire.com/file/gil2yjvlxudmyir/Toontown-macOS-sv1.0.47.31-master.zip/file
You can also find it on my GitHub:
https://github.com/CloudCityDev/Toontown-macOS-sv1.0.47.31

**Comment by JoeyZio** [comment]
Thanks a bunch for taking the time to upload this - I would definitely call it a significant release.

I added it to the repository in 82e0eb87. Let me know or submit a pull request if you'd like to be credited by a different name!
