### ISSUE TITLE
More macOS Client Contributions

### ISSUE THREAD

**Issue by CloudCityDev** [ToontownRewritten/ToontownReleaseArchive#33]
I have three more macOS clients, for a total of four released macOS clients thus far. These include the final live client, the final test client, and the client that patched the bot issue.

macOS sv1.0.48.6 - Final Test Client (macOS) | February 17, 2012 - https://github.com/CloudCityDev/Toontown-macOS-sv1.0.48.6
macOS sv1.0.47.38 - Final Live Client (macOS) | August 10, 2013 - https://github.com/CloudCityDev/Toontown-macOS-sv1.0.47.38
macOS sv1.0.47.35 - Client that patched the bots (macOS) | August 2, 2013 - https://github.com/CloudCityDev/Toontown-macOS-sv1.0.47.35

**Comment by JoeyZio** [comment]
Thank you for these donations @CloudCityDev! Merged in 6ff5f47.
