### ISSUE TITLE
Contribution - Toontown France 2005 CD-ROM

### ISSUE THREAD

**Issue by NathaanTFM** [ToontownRewritten/ToontownReleaseArchive#6]
Hey,
Just sharing the contents of the Toontown France 2005 CD-ROM. Found it on eBay and dumped it myself.

https://drive.google.com/file/d/10_3y1Fp-B7PsTPQa-6DuDTscqmPzRKsz/view?usp=sharing

Seems to be a build from late November 2003? Also contains dna and textures from other localizations

(EDIT: The build is from 2005, but based on panda3d repo, the code is from 2003)

**Comment by furtabs** [comment]
This is a new client. Thank you for sharing. I can help set up a PR for you.

**Comment by furtabs** [comment]
sv1.5.8.16
