### ISSUE TITLE
Contribution - Toontown France 2009 Client

### ISSUE THREAD

**Issue by NathaanTFM** [ToontownRewritten/ToontownReleaseArchive#7]
Someone gave me this client in 2017. They also have added files. I never looked at it. This is the original archive they gave me

https://drive.google.com/file/d/1r7O9g2TSt28t95pzVVzaLQ1Nl0iyfBOO/view?usp=sharing

**Comment by furtabs** [comment]
Probally a reupload of John Cote's 2009 Client but ill take a peek for you. Im going to add a script later to check versions yourself.

**Comment by furtabs** [comment]
Ill take back what i said. Its a new client as well. Thank you for the donation. It is sv1.5.26.8
